//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuestas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Respuestas()
        {
            this.Resultados = new HashSet<Resultados>();
        }
    
        public int IdT_Respuesta { get; set; }
        public int IdF_Pregunta { get; set; }
        public int IdF_Prueba { get; set; }
        public string IdF_Usuario { get; set; }
        public string TituloRespuesta { get; set; }
        public string TextoRespuesta { get; set; }
        public bool Correcto { get; set; }
        public decimal Ponderacion { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Preguntas Preguntas { get; set; }
        public virtual Pruebas Pruebas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resultados> Resultados { get; set; }
    }
}
