//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultados
    {
        public int IdT_Resultado { get; set; }
        public int IdF_Respuesta { get; set; }
        public int IdF_Prueba { get; set; }
        public int Intento { get; set; }
    
        public virtual Pruebas Pruebas { get; set; }
        public virtual Respuestas Respuestas { get; set; }
    }
}
